import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    scrollViewContainer: {
        flex: 1,
      
        paddingTop: 20,
        paddingBottom: 20,
      },
      scrollViewContent: {
        alignItems: 'center', 
        paddingBottom: 100, 
      },
      streakContainer: {
        marginVertical: 10,
        alignItems: "center",
        marginBottom: 20,
      },
      streakText: {
        fontSize: 16,
        color: "#666",
        marginBottom: 20,
      },
      streakDaysContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: 200,
      },
      streakDay: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "#E0E0E0",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 20,
      },
      streakDayActive: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: "#4CAF50",
        justifyContent: "center",
        alignItems: "center",
      },
      checkmark: {
        fontSize: 20,
        color: "#FFF",
        position: "absolute",
      },
      streakDayText: {
        fontSize: 14,
        color: "#FFF",
        fontWeight: "bold",
      },
      statsContainer: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 40,
        width: "100%",
      },
      statItem: {
        backgroundColor: '#fff',
        borderRadius: 5,
        paddingHorizontal: 12,
        paddingVertical:6,
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width:0, height:1 },
        shadowOpacity:0.2,
        shadowRadius: 2,
        elevation: 2,
      },
      statLabel: {
        fontSize: 14,
        color: "#666",
      },
      statValue: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#333",
      },
      sectionContainer: {
        marginTop: 40,
        width: '100%',
        paddingHorizontal: 10,
      },
      sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 10,
        marginBottom: 10,
        color: '#333',
      },
      taskContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        flexWrap: 'wrap',
      },
      taskCard: {
        width: '30%',
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 10,
        marginBottom: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
        backgroundColor: '#fff',
        overflow: 'hidden',
      },
      taskImage: {
        width: '100%',
        height: 100, 
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
      },
      rewardContainer: {
        backgroundColor: '#fff',
        borderRadius: 5,
        paddingHorizontal: 8,
        paddingVertical:4,
        position: 'absolute',
        top: 5,
        left: 5,
        shadowColor: '#000',
        shadowOffset: { width:0, height:1 },
        shadowOpacity:0.2,
        shadowRadius: 2,
        elevation: 2,
      },
      taskReward: {
        fontSize: 14,
        color: '#333',
        fontWeight: 'bold',
      },
      taskTextContainer: {
        backgroundColor: '#fff',
        padding: 10,
        alignItems: 'center',
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
      },
      taskTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        textAlign:'center',
      },
      taskSpins: {
        fontSize: 12,
        color: '#888',
      },
      taskCompleted: {
        fontSize: 12,
        color: 'green',
        marginTop: 5,
      },
      
      modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 15,
        width: 300,
        height: 200,
        padding: 15,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    modalTitleBox:{
    backgroundColor: '#ffff69',
    width: 200,
    height: 30,
    fontSize: 30,
    borderRadius:5,
    marginBottom:50,
    justifyContent: 'center',
    alignItems: 'center',
    },
    modalText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000000',
        textAlign: 'center',
    },
    modalButton: {
        width: 40,
        height: 40,
        backgroundColor: '#fafafa',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#000000',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 40,
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    modalButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#000',
    },
});