import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E6F0FA',
    paddingTop: 20,
    alignItems: 'center',
    paddingBottom: 20,
  },
  circleContainer: {
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  stepsOverlay: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
  },
  stepsText: {
    fontSize: 60,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginTop: 50,
  },
  stepsLabel: {
    fontSize:20,
    color: '#666', 
    textAlign: 'center',
    marginTop: 5,
  },
  goalContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 80,
    marginBottom: 20,
  },
  goalText: {
    fontSize: 18,
    marginTop: 20,
    marginBottom: 50,
  },
  progressText: {
    fontSize: 16,
    marginTop: 10,
  },
  buttonConvertText: {
    color: '#FFFFFF', 
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonConvert: {
    width: 250,
    height: 60,
    borderRadius: 10,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  coinButton: {
    width: 140,
    height: 50,
    backgroundColor: '#FFC107',
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  giftShopButton: {
    width: 120,
    height: 50,
    backgroundColor: '#FF69B4',
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  buttonText: {
    color: '#000000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  topLeftContainer: {
    position: 'absolute', 
    top: 100, 
    left: 20, 
  },
  topRightContainer: {
  position: 'absolute',
  top: 30,
  right: 20,
},
  containershop: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    paddingTop: 20,
    alignItems: 'center',
  },
  titleshop: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  subtitleshop: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
},
modalContent: {
    backgroundColor: 'white',
    borderRadius: 15,
    width: 300,
    height: 200,
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
},
modalTitleBox:{
backgroundColor: '#ffff69',
width: 200,
height: 30,
fontSize: 30,
borderRadius:5,
marginBottom:50,
justifyContent: 'center',
alignItems: 'center',
},
modalText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
},
modalButton: {
    width: 40,
    height: 40,
    backgroundColor: '#fafafa',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
},
modalButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
},
userContainer: {
  flexDirection: "row", 
  alignItems: "center",
  justifyContent: 'flex-start',
  marginTop: 20,
  marginBottom: 20,
  paddingRight: 190,
},
userImage: {
  width: 80,
  height: 80,
  borderRadius: 40,
  marginRight: 30,
  
},
placeholderImage: {
  width: 50,
  height: 50,
  borderRadius: 25,
  backgroundColor: "#ccc",
  justifyContent: "center",
  alignItems: "center",
  marginLeft: 10,
},
placeholderText: {
  color: "#fff",
  fontSize: 10,
},
textContainer: {
  flexDirection: "column", 
  justifyContent: "center",
},
helloText: {
  fontSize: 20,
  fontWeight: "bold",
  color: "#333",
  marginBottom: 5,
},

streakContainer: {
    marginVertical: 10,
    alignItems: "center",
    marginBottom: 20,
  },
  streakText: {
    fontSize: 16,
    color: "#666",
    marginBottom: 20,
  },
  streakDaysContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: 200,
  },
  streakDay: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#E0E0E0",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  streakDayActive: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#4CAF50",
    justifyContent: "center",
    alignItems: "center",
  },
  streakDayText: {
    fontSize: 14,
    color: "#FFF",
    fontWeight: "bold",
  },
  checkmark: {
    fontSize: 20,
    color: "#FFF",
    position: "absolute",
  },
  goalMarker: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E0E0E0",
    justifyContent: "center",
    alignItems: "center",
  },
  goalMarkerAchieved: {
    backgroundColor: "#4CAF50",
  },
  goalMarkerText: {
    fontSize: 12,
    color: "#FFF",
    fontWeight: "bold",
  },
  goalReward: {
    marginTop: 5,
    backgroundColor: "#FFF",
    borderRadius: 10,
    padding: 2,
  },
  goalRewardText: {
    fontSize: 12,
    color: "#333",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 20,
    width: "100%",
  },
  statItem: {
    alignItems: "center",
  },
  statLabel: {
    fontSize: 14,
    color: "#666",
  },
  statValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },

});