import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  
  circleContainer: {
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  stepsOverlay: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    fontWeight: 'bold',
  },
  stepsText: {
    fontSize: 60,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginTop: 50,
  },
  stepsLabel: {
    fontSize:20,
    color: '#666', 
    textAlign: 'center',
    marginTop: 5,
  },
  goalContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 80,
    marginBottom: 20,
  },
  goalText: {
    fontSize: 18,
    marginTop: 20,
    marginBottom: 50,
  },
  progressText: {
    fontSize: 16,
    marginTop: 10,
  },
  buttonConvertText: {
    color: '#FFFFFF', 
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttonConvert: {
    width: 250,
    height: 60,
    borderRadius: 10,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  coinButton: {
    width: 140,
    height: 50,
    backgroundColor: '#FFC107',
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  containershop: {
    flex: 1,
    backgroundColor: '#F5F5F5',
    paddingTop: 20,
    alignItems: 'center',
  },
  titleshop: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  subtitleshop: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 20,
  },
 
placeholderText: {
  color: "#fff",
  fontSize: 10,
},
textContainer: {
  flexDirection: "column", 
  justifyContent: "center",
},
helloText: {
  fontSize: 20,
  fontWeight: "bold",
  color: "#333",
  marginBottom: 5,
},
  goalMarker: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E0E0E0",
    justifyContent: "center",
    alignItems: "center",
  },
  goalMarkerAchieved: {
    backgroundColor: "#4CAF50",
  },
  goalMarkerText: {
    fontSize: 12,
    color: "#FFF",
    fontWeight: "bold",
  },
  goalReward: {
    marginTop: 5,
    backgroundColor: "#FFF",
    borderRadius: 10,
    padding: 2,
  },
  goalRewardText: {
    fontSize: 12,
    color: "#333",
  },
  navBarContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    paddingVertical: 15,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  statWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 8,
    position: 'relative',
  },
  iconWrapper: {
    zIndex: 2,
    marginRight: -12, 
  },
  iconNav: {
    fontSize: 35,
  },
  navBarItem: {
    backgroundColor: '#717787',
    width: 60,
    height: 28,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  navBarText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ffffff",
  },
 
 

 
  areaContainer: {
    flex: 1,
    backgroundColor: '#ba55d3',
  },
  rewardsContainer: {
    marginTop: 20,
    backgroundColor: 'transparent',
    justifyContent:'center',
    alignContent: 'center',
    width: '100%',
  },
  redeemButton: {
    backgroundColor: '#ffffff',
    paddingVertical: 15,
    paddingHorizontal: 30,
    marginHorizontal: 40,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ccc',
    marginBottom: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  redeemButtonText: {
    color: '#565656',
    fontSize: 18,
    fontWeight: 'bold',
  },
  rewardsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  rewardCard: {
    backgroundColor: '#D6E8FF',
    borderRadius: 10,
    padding: 15,
    width: '48%',
    marginBottom: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    justifyContent: 'center',
  },
  rewardText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
  },
  amountText: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#333',
    marginVertical: 5,
    marginTop: 5,
  },
  coinsContainer: {
    backgroundColor: '#28A745',
    borderColor: '#ccc',
    borderWidth: 2,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    paddingVertical: 8,
    paddingHorizontal: 10,
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  coinsText: {
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    width: '90%',
    alignItems: 'center',
  },
  modalHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  modalAmount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#007AFF',
    marginTop: 5,
  },
  emailInput: {
    width: '100%',
    padding: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    marginBottom: 20,
    backgroundColor: '#E6F0FA',
  },
  confirmButton: {
    backgroundColor: '#34C759',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    marginBottom: 10,
  },
  confirmButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  whyLink: {
    marginTop: 10,
  },
  whyLinkText: {
    fontSize: 14,
    color: '#007AFF',
    textDecorationLine: 'underline',
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  closeButtonText: {
    fontSize: 24,
    color: '#FF3B30',
  },
  pickerModalContent: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 30,
    width: '90%',
    alignItems: 'center',
  },
  pickerContainer: {
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    backgroundColor: '#E6F0FA',
    width: '100%',
  },
  picker: {
    height: 150,
    width: '100%',
  },
  activimentContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 25,
    paddingHorizontal: 20,
    backgroundColor: '#f5fffa',
    borderRadius: 10,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  actContainer:{
    width: '80%',
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 5,
    marginVertical: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  actTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      textAlign: 'center',
      marginVertical: 20,
      color: '#333',
  },
  actItem: {
    marginVertical: 10,
    alignItems: 'center',
    padding: 10,
    width: '90%',
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
  },
  actLabel: {
    fontSize: 18,
    color: '#555',
    marginBottom: 5,
  },
  actValue: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
  }
});